#
# codebeat model builder scripts - a set of scripts to build models used for code smells detection in codebeat
# Copyright (C) 2018-2022 code quest sp. z o.o.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

libs <- c("https://cloud.r-project.org/src/contrib/formatR_1.7.tar.gz",
"https://cloud.r-project.org/src/contrib/lpSolve_5.6.13.3.tar.gz",
"https://cloud.r-project.org/src/contrib/linprog_0.9-2.tar.gz",
"https://cloud.r-project.org/src/contrib/RcppProgress_0.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/permute_0.9-5.tar.gz",
"https://cloud.r-project.org/src/contrib/NADA_1.6-1.tar.gz",
"https://cloud.r-project.org/src/contrib/truncnorm_1.0-8.tar.gz",
"https://cloud.r-project.org/src/contrib/zeallot_0.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/fontBitstreamVera_0.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/fontLiberation_0.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/systemfonts_0.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/lambda.r_1.2.4.tar.gz",
"https://cloud.r-project.org/src/contrib/futile.options_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/profileModel_0.6.0.tar.gz",
"https://cloud.r-project.org/src/contrib/zip_2.0.4.tar.gz",
"https://cloud.r-project.org/src/contrib/showimage_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/ape_5.3.tar.gz",
"https://cloud.r-project.org/src/contrib/geometry_0.4.4.tar.gz",
"https://cloud.r-project.org/src/contrib/vegan_2.5-6.tar.gz",
"https://cloud.r-project.org/src/contrib/cubature_2.0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/extrafontdb_1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/Rttf2pt1_1.3.7.tar.gz",
"https://cloud.r-project.org/src/contrib/GlobalOptions_0.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/gdata_2.18.0.tar.gz",
"https://cloud.r-project.org/src/contrib/caTools_1.17.1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/rngWELL_0.10-5.tar.gz",
"https://cloud.r-project.org/src/contrib/Rook_1.1-1.tar.gz",
"https://cloud.r-project.org/src/contrib/bibtex_0.4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/gbRd_0.4-11.tar.gz",
"https://cloud.r-project.org/src/contrib/polspline_1.1.17.tar.gz",
"https://cloud.r-project.org/src/contrib/SQUAREM_2017.10-1.tar.gz",
"https://cloud.r-project.org/src/contrib/dbscan_1.1-5.tar.gz",
"https://cloud.r-project.org/src/contrib/cvTools_0.3.2.tar.gz",
"https://cloud.r-project.org/src/contrib/sROC_0.1-2.tar.gz",
"https://cloud.r-project.org/src/contrib/zCompositions_1.3.2-1.tar.gz",
"https://cloud.r-project.org/src/contrib/matrixStats_0.55.0.tar.gz",
"https://cloud.r-project.org/src/contrib/praise_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/generics_0.0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/gower_0.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/timeDate_3043.102.tar.gz",
"https://cloud.r-project.org/src/contrib/highr_0.8.tar.gz",
"https://cloud.r-project.org/src/contrib/xfun_0.10.tar.gz",
"https://cloud.r-project.org/src/contrib/labeling_0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/munsell_0.5.0.tar.gz",
"https://cloud.r-project.org/src/contrib/tinytex_0.17.tar.gz",
"https://cloud.r-project.org/src/contrib/vctrs_0.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/lifecycle_0.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/diffobj_0.2.3.tar.gz",
"https://cloud.r-project.org/src/contrib/fontquiver_0.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/freetypeharfbuzz_0.2.5.tar.gz",
"https://cloud.r-project.org/src/contrib/gdtools_0.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/futile.logger_1.4.3.tar.gz",
"https://cloud.r-project.org/src/contrib/iterators_1.0.12.tar.gz",
"https://cloud.r-project.org/src/contrib/brglm_0.6.2.tar.gz",
"https://cloud.r-project.org/src/contrib/gtools_3.8.1.tar.gz",
"https://cloud.r-project.org/src/contrib/qvcalc_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/ISwR_2.0-7.tar.gz",
"https://cloud.r-project.org/src/contrib/fansi_0.4.0.tar.gz",
"https://cloud.r-project.org/src/contrib/hunspell_3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/openxlsx_4.1.3.tar.gz",
"https://cloud.r-project.org/src/contrib/minqa_1.2.4.tar.gz",
"https://cloud.r-project.org/src/contrib/nloptr_1.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/effects_4.1-3.tar.gz",
"https://cloud.r-project.org/src/contrib/bdsmatrix_1.3-3.tar.gz",
"https://cloud.r-project.org/src/contrib/manipulateWidget_0.10.0.tar.gz",
"https://cloud.r-project.org/src/contrib/mitools_2.4.tar.gz",
"https://cloud.r-project.org/src/contrib/DEoptimR_1.0-8.tar.gz",
"https://cloud.r-project.org/src/contrib/itertools_0.1-3.tar.gz",
"https://cloud.r-project.org/src/contrib/bit_1.1-14.tar.gz",
"https://cloud.r-project.org/src/contrib/prettyunits_1.0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/xopen_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/gargle_0.4.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rematch2_2.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/cyclocomp_1.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/xmlparsedata_1.0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/highlight_0.4.7.2.tar.gz",
"https://cloud.r-project.org/src/contrib/parsedate_1.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rematch_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/uuid_0.1-2.tar.gz",
"https://cloud.r-project.org/src/contrib/whoami_1.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/progress_1.2.2.tar.gz",
"https://cloud.r-project.org/src/contrib/reshape_0.8.8.tar.gz",
"https://cloud.r-project.org/src/contrib/debugme_1.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/webdriver_1.0.5.tar.gz",
"https://cloud.r-project.org/src/contrib/classInt_0.4-2.tar.gz",
"https://cloud.r-project.org/src/contrib/units_0.6-5.tar.gz",
"https://cloud.r-project.org/src/contrib/repr_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/ps_1.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/measures_0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/Deriv_3.9.0.tar.gz",
"https://cloud.r-project.org/src/contrib/sys_3.3.tar.gz",
"https://cloud.r-project.org/src/contrib/fastmatch_1.1-0.tar.gz",
"https://cloud.r-project.org/src/contrib/misc3d_0.8-4.tar.gz",
"https://cloud.r-project.org/src/contrib/utf8_1.1.4.tar.gz",
"https://cloud.r-project.org/src/contrib/R.cache_0.13.0.tar.gz",
"https://cloud.r-project.org/src/contrib/base64url_1.4.tar.gz",
"https://cloud.r-project.org/src/contrib/FD_1.0-12.tar.gz",
"https://cloud.r-project.org/src/contrib/ade4_1.7-13.tar.gz",
"https://cloud.r-project.org/src/contrib/R2HTML_2.3.2.tar.gz",
"https://cloud.r-project.org/src/contrib/np_0.60-9.tar.gz",
"https://cloud.r-project.org/src/contrib/gamboostLSS_2.0-1.tar.gz",
"https://cloud.r-project.org/src/contrib/stabs_0.6-3.tar.gz",
"https://cloud.r-project.org/src/contrib/mclust_5.4.5.tar.gz",
"https://cloud.r-project.org/src/contrib/flexmix_2.3-15.tar.gz",
"https://cloud.r-project.org/src/contrib/prabclus_2.3-1.tar.gz",
"https://cloud.r-project.org/src/contrib/diptest_0.75-7.tar.gz",
"https://cloud.r-project.org/src/contrib/ggrepel_0.8.1.tar.gz",
"https://cloud.r-project.org/src/contrib/ggsci_2.9.tar.gz",
"https://cloud.r-project.org/src/contrib/ggsignif_0.6.0.tar.gz",
"https://cloud.r-project.org/src/contrib/polynom_1.4-0.tar.gz",
"https://cloud.r-project.org/src/contrib/latticeExtra_0.6-28.tar.gz",
"https://cloud.r-project.org/src/contrib/acepack_1.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/htmlTable_1.13.2.tar.gz",
"https://cloud.r-project.org/src/contrib/extrafont_0.17.tar.gz",
"https://cloud.r-project.org/src/contrib/nnls_1.4.tar.gz",
"https://cloud.r-project.org/src/contrib/quadprog_1.5-7.tar.gz",
"https://cloud.r-project.org/src/contrib/circlize_0.4.8.tar.gz",
"https://cloud.r-project.org/src/contrib/magic_1.5-9.tar.gz",
"https://cloud.r-project.org/src/contrib/gamm4_0.2-5.tar.gz",
"https://cloud.r-project.org/src/contrib/RLRsim_3.1-3.tar.gz",
"https://cloud.r-project.org/src/contrib/grpreg_3.2-1.tar.gz",
"https://cloud.r-project.org/src/contrib/pbs_1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/gplots_3.0.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/estimability_1.3.tar.gz",
"https://cloud.r-project.org/src/contrib/maptree_1.4-7.tar.gz",
"https://cloud.r-project.org/src/contrib/randtoolbox_1.30.0.tar.gz",
"https://cloud.r-project.org/src/contrib/pbivnorm_0.6.0.tar.gz",
"https://cloud.r-project.org/src/contrib/mnormt_1.5-5.tar.gz",
"https://cloud.r-project.org/src/contrib/DiceDesign_1.8-1.tar.gz",
"https://cloud.r-project.org/src/contrib/sendmailR_1.2-1.tar.gz",
"https://cloud.r-project.org/src/contrib/cellranger_1.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/downloader_0.4.tar.gz",
"https://cloud.r-project.org/src/contrib/influenceR_0.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rgexf_0.15.3.tar.gz",
"https://cloud.r-project.org/src/contrib/visNetwork_2.0.8.tar.gz",
"https://cloud.r-project.org/src/contrib/Rdpack_0.11-0.tar.gz",
"https://cloud.r-project.org/src/contrib/flashClust_1.01-2.tar.gz",
"https://cloud.r-project.org/src/contrib/miniUI_0.1.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/labelled_2.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/rms_5.1-3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/timereg_1.9.4.tar.gz",
"https://cloud.r-project.org/src/contrib/lava_1.6.6.tar.gz",
"https://cloud.r-project.org/src/contrib/bnlearn_4.5.tar.gz",
"https://cloud.r-project.org/src/contrib/KernelKnn_1.0.9.tar.gz",
"https://cloud.r-project.org/src/contrib/smotefamily_1.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/sgeostat_1.0-27.tar.gz",
"https://cloud.r-project.org/src/contrib/robCompositions_2.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/Formula_1.2-3.tar.gz",
"https://cloud.r-project.org/src/contrib/pmml_2.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/sandwich_2.5-1.tar.gz",
"https://cloud.r-project.org/src/contrib/strucchange_1.5-2.tar.gz",
"https://cloud.r-project.org/src/contrib/vcd_1.4-4.tar.gz",
"https://cloud.r-project.org/src/contrib/AER_1.2-8.tar.gz",
"https://cloud.r-project.org/src/contrib/mlbench_2.1-1.tar.gz",
"https://cloud.r-project.org/src/contrib/TH.data_1.0-10.tar.gz",
"https://cloud.r-project.org/src/contrib/coin_1.3-1.tar.gz",
"https://cloud.r-project.org/src/contrib/psychotools_0.5-0.tar.gz",
"https://cloud.r-project.org/src/contrib/psychotree_0.15-2.tar.gz",
"https://cloud.r-project.org/src/contrib/RColorBrewer_1.1-2.tar.gz",
"https://cloud.r-project.org/src/contrib/testthat_2.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/yaml_2.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/data.table_1.12.6.tar.gz",
"https://cloud.r-project.org/src/contrib/stringdist_0.9.5.5.tar.gz",
"https://cloud.r-project.org/src/contrib/pipeR_0.6.1.3.tar.gz",
"https://cloud.r-project.org/src/contrib/Cubist_0.2.2.tar.gz",
"https://cloud.r-project.org/src/contrib/recipes_0.1.7.tar.gz",
"https://cloud.r-project.org/src/contrib/knitr_1.25.tar.gz",
"https://cloud.r-project.org/src/contrib/ggplot2_3.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/gtable_0.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rlang_0.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/scales_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/Cairo_1.5-10.tar.gz",
"https://cloud.r-project.org/src/contrib/forcats_0.4.0.tar.gz",
"https://cloud.r-project.org/src/contrib/gridGraphics_0.4-1.tar.gz",
"https://cloud.r-project.org/src/contrib/magick_2.2.tar.gz",
"https://cloud.r-project.org/src/contrib/maps_3.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/PASWR_1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/rmarkdown_1.16.tar.gz",
"https://cloud.r-project.org/src/contrib/tidyr_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/vdiffr_0.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/VennDiagram_1.6.20.tar.gz",
"https://cloud.r-project.org/src/contrib/RWekajars_3.9.3-2.tar.gz",
"https://cloud.r-project.org/src/contrib/foreach_1.4.7.tar.gz",
"https://cloud.r-project.org/src/contrib/plyr_1.8.4.tar.gz",
"https://cloud.r-project.org/src/contrib/reshape2_1.4.3.tar.gz",
"https://cloud.r-project.org/src/contrib/withr_2.1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/BradleyTerry2_1.1-0.tar.gz",
"https://cloud.r-project.org/src/contrib/fastICA_1.2-2.tar.gz",
"https://cloud.r-project.org/src/contrib/gam_1.16.1.tar.gz",
"https://cloud.r-project.org/src/contrib/ipred_0.9-9.tar.gz",
"https://cloud.r-project.org/src/contrib/ellipse_0.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/MLmetrics_1.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/pROC_1.15.3.tar.gz",
"https://cloud.r-project.org/src/contrib/proxy_0.4-23.tar.gz",
"https://cloud.r-project.org/src/contrib/RANN_2.6.1.tar.gz",
"https://cloud.r-project.org/src/contrib/spls_2.2-3.tar.gz",
"https://cloud.r-project.org/src/contrib/subselect_0.14.tar.gz",
"https://cloud.r-project.org/src/contrib/pamr_1.56.1.tar.gz",
"https://cloud.r-project.org/src/contrib/superpc_1.09.tar.gz",
"https://cloud.r-project.org/src/contrib/R.oo_1.23.0.tar.gz",
"https://cloud.r-project.org/src/contrib/R.methodsS3_1.7.1.tar.gz",
"https://cloud.r-project.org/src/contrib/digest_0.6.22.tar.gz",
"https://cloud.r-project.org/src/contrib/Rcpp_1.0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/tibble_2.1.3.tar.gz",
"https://cloud.r-project.org/src/contrib/hms_0.5.2.tar.gz",
"https://cloud.r-project.org/src/contrib/R6_2.4.0.tar.gz",
"https://cloud.r-project.org/src/contrib/clipr_0.7.0.tar.gz",
"https://cloud.r-project.org/src/contrib/crayon_1.3.4.tar.gz",
"https://cloud.r-project.org/src/contrib/BH_1.69.0-1.tar.gz",
"https://cloud.r-project.org/src/contrib/stringi_1.4.3.tar.gz",
"https://cloud.r-project.org/src/contrib/spelling_2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/carData_3.0-2.tar.gz",
"https://cloud.r-project.org/src/contrib/abind_1.4-5.tar.gz",
"https://cloud.r-project.org/src/contrib/pbkrtest_0.4-7.tar.gz",
"https://cloud.r-project.org/src/contrib/quantreg_5.52.tar.gz",
"https://cloud.r-project.org/src/contrib/maptools_0.9-8.tar.gz",
"https://cloud.r-project.org/src/contrib/rio_0.5.16.tar.gz",
"https://cloud.r-project.org/src/contrib/lme4_1.1-21.tar.gz",
"https://cloud.r-project.org/src/contrib/alr4_1.0.6.tar.gz",
"https://cloud.r-project.org/src/contrib/coxme_2.2-14.tar.gz",
"https://cloud.r-project.org/src/contrib/leaps_3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/lmtest_0.9-37.tar.gz",
"https://cloud.r-project.org/src/contrib/MatrixModels_0.4-1.tar.gz",
"https://cloud.r-project.org/src/contrib/rgl_0.100.30.tar.gz",
"https://cloud.r-project.org/src/contrib/SparseM_1.77.tar.gz",
"https://cloud.r-project.org/src/contrib/survey_3.36.tar.gz",
"https://cloud.r-project.org/src/contrib/robustbase_0.93-5.tar.gz",
"https://cloud.r-project.org/src/contrib/pcaPP_1.9-73.tar.gz",
"https://cloud.r-project.org/src/contrib/colorspace_1.4-1.tar.gz",
"https://cloud.r-project.org/src/contrib/sp_1.3-2.tar.gz",
"https://cloud.r-project.org/src/contrib/laeken_0.5.0.tar.gz",
"https://cloud.r-project.org/src/contrib/bartMachineJARs_1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/missForest_1.4.tar.gz",
"https://cloud.r-project.org/src/contrib/slam_0.1-46.tar.gz",
"https://cloud.r-project.org/src/contrib/bit64_0.9-7.tar.gz",
"https://cloud.r-project.org/src/contrib/plot3Drgl_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/bitops_1.0-6.tar.gz",
"https://cloud.r-project.org/src/contrib/xtable_1.8-4.tar.gz",
"https://cloud.r-project.org/src/contrib/expm_0.999-4.tar.gz",
"https://cloud.r-project.org/src/contrib/assertthat_0.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/glue_1.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/magrittr_1.5.tar.gz",
"https://cloud.r-project.org/src/contrib/pkgconfig_2.0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/tidyselect_0.2.5.tar.gz",
"https://cloud.r-project.org/src/contrib/plogr_0.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/callr_3.3.2.tar.gz",
"https://cloud.r-project.org/src/contrib/DBI_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/dbplyr_1.4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/dtplyr_0.0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/Lahman_7.0-1.tar.gz",
"https://cloud.r-project.org/src/contrib/lubridate_1.7.4.tar.gz",
"https://cloud.r-project.org/src/contrib/microbenchmark_1.4-7.tar.gz",
"https://cloud.r-project.org/src/contrib/nycflights13_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/RMySQL_0.10.17.tar.gz",
"https://cloud.r-project.org/src/contrib/RPostgreSQL_0.6-2.tar.gz",
"https://cloud.r-project.org/src/contrib/RSQLite_2.1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/broom_0.5.2.tar.gz",
"https://cloud.r-project.org/src/contrib/purrr_0.3.3.tar.gz",
"https://cloud.r-project.org/src/contrib/cli_1.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/desc_1.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/DT_0.9.tar.gz",
"https://cloud.r-project.org/src/contrib/ellipsis_0.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/memoise_1.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/pkgbuild_1.0.6.tar.gz",
"https://cloud.r-project.org/src/contrib/pkgload_1.0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/rcmdcheck_1.3.3.tar.gz",
"https://cloud.r-project.org/src/contrib/remotes_2.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/sessioninfo_1.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/BiocManager_1.30.9.tar.gz",
"https://cloud.r-project.org/src/contrib/evaluate_0.14.tar.gz",
"https://cloud.r-project.org/src/contrib/foghorn_1.1.3.tar.gz",
"https://cloud.r-project.org/src/contrib/gmailr_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/lintr_2.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/mockery_0.4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/pingr_2.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/pkgdown_1.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/rhub_1.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/whisker_0.4.tar.gz",
"https://cloud.r-project.org/src/contrib/TeachingDemos_2.10.tar.gz",
"https://cloud.r-project.org/src/contrib/mime_0.7.tar.gz",
"https://cloud.r-project.org/src/contrib/httpuv_1.5.2.tar.gz",
"https://cloud.r-project.org/src/contrib/jpeg_0.1-8.1.tar.gz",
"https://cloud.r-project.org/src/contrib/png_0.1-7.tar.gz",
"https://cloud.r-project.org/src/contrib/ini_0.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/viridisLite_0.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/base64enc_0.1-3.tar.gz",
"https://cloud.r-project.org/src/contrib/htmltools_0.4.0.tar.gz",
"https://cloud.r-project.org/src/contrib/htmlwidgets_1.5.1.tar.gz",
"https://cloud.r-project.org/src/contrib/hexbin_1.27.3.tar.gz",
"https://cloud.r-project.org/src/contrib/lazyeval_0.2.2.tar.gz",
"https://cloud.r-project.org/src/contrib/crosstalk_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/promises_1.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/ggthemes_4.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/GGally_1.4.0.tar.gz",
"https://cloud.r-project.org/src/contrib/shinytest_1.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/webshot_0.5.1.tar.gz",
"https://cloud.r-project.org/src/contrib/listviewer_3.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/dendextend_1.12.0.tar.gz",
"https://cloud.r-project.org/src/contrib/sf_0.8-0.tar.gz",
"https://cloud.r-project.org/src/contrib/rgeos_0.5-2.tar.gz",
"https://cloud.r-project.org/src/contrib/IRdisplay_0.7.0.tar.gz",
"https://cloud.r-project.org/src/contrib/processx_3.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/plotlyGeoAssets_0.0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/modeltools_0.2-22.tar.gz",
"https://cloud.r-project.org/src/contrib/zoo_1.8-6.tar.gz",
"https://cloud.r-project.org/src/contrib/varImp_0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/clisymbols_1.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rprojroot_1.3-2.tar.gz",
"https://cloud.r-project.org/src/contrib/styler_1.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rex_1.1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/brew_1.0-6.tar.gz",
"https://cloud.r-project.org/src/contrib/commonmark_1.7.tar.gz",
"https://cloud.r-project.org/src/contrib/glmnetUtils_1.1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/neuralnet_1.44.2.tar.gz",
"https://cloud.r-project.org/src/contrib/pre_0.7.1.tar.gz",
"https://cloud.r-project.org/src/contrib/askpass_1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/webutils_1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/jose_1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/sodium_1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/ParamHelpers_1.12.tar.gz",
"https://cloud.r-project.org/src/contrib/BBmisc_1.11.tar.gz",
"https://cloud.r-project.org/src/contrib/checkmate_1.9.4.tar.gz",
"https://cloud.r-project.org/src/contrib/plot3D_1.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/mco_1.0-15.1.tar.gz",
"https://cloud.r-project.org/src/contrib/RJSONIO_1.3-1.3.tar.gz",
"https://cloud.r-project.org/src/contrib/RcppArmadillo_0.9.800.1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rPython_0.0-6.tar.gz",
"https://cloud.r-project.org/src/contrib/selectr_0.4-1.tar.gz",
"https://cloud.r-project.org/src/contrib/pillar_1.4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/gridExtra_2.3.tar.gz",
"https://cloud.r-project.org/src/contrib/pdp_0.7.0.tar.gz",
"https://cloud.r-project.org/src/contrib/RUnit_0.4.32.tar.gz",
"https://cloud.r-project.org/src/contrib/viridis_0.5.1.tar.gz",
"https://cloud.r-project.org/src/contrib/getPass_0.2-2.tar.gz",
"https://cloud.r-project.org/src/contrib/sourcetools_0.1.7.tar.gz",
"https://cloud.r-project.org/src/contrib/later_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/fastmap_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/markdown_1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/reactlog_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/shape_1.4.4.tar.gz",
"https://cloud.r-project.org/src/contrib/lars_1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/R.rsp_0.43.2.tar.gz",
"https://cloud.r-project.org/src/contrib/igraph_1.2.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/backports_1.1.5.tar.gz",
"https://cloud.r-project.org/src/contrib/batchtools_0.9.11.tar.gz",
"https://cloud.r-project.org/src/contrib/brnn_0.7.tar.gz",
"https://cloud.r-project.org/src/contrib/bst_0.3-17.tar.gz",
"https://cloud.r-project.org/src/contrib/care_1.1.10.tar.gz",
"https://cloud.r-project.org/src/contrib/clue_0.3-57.tar.gz",
"https://cloud.r-project.org/src/contrib/ClusterR_1.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/clusterSim_0.48-1.tar.gz",
"https://cloud.r-project.org/src/contrib/clValid_0.6-6.tar.gz",
"https://cloud.r-project.org/src/contrib/cmaes_1.0-11.tar.gz",
"https://cloud.r-project.org/src/contrib/CoxBoost_1.4.tar.gz",
"https://cloud.r-project.org/src/contrib/crs_0.15-31.tar.gz",
"https://cloud.r-project.org/src/contrib/DiceKriging_1.5.6.tar.gz",
"https://cloud.r-project.org/src/contrib/emoa_0.5-0.tar.gz",
"https://cloud.r-project.org/src/contrib/FDboost_0.3-2.tar.gz",
"https://cloud.r-project.org/src/contrib/flare_1.6.0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/fpc_2.2-3.tar.gz",
"https://cloud.r-project.org/src/contrib/frbs_3.1-0.tar.gz",
"https://cloud.r-project.org/src/contrib/FSelector_0.31.tar.gz",
"https://cloud.r-project.org/src/contrib/FSelectorRcpp_0.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/GenSA_1.1.7.tar.gz",
"https://cloud.r-project.org/src/contrib/ggpubr_0.2.3.tar.gz",
"https://cloud.r-project.org/src/contrib/GPfit_1.0-8.tar.gz",
"https://cloud.r-project.org/src/contrib/Hmisc_4.3-0.tar.gz",
"https://cloud.r-project.org/src/contrib/hrbrthemes_0.6.0.tar.gz",
"https://cloud.r-project.org/src/contrib/irace_3.3.tar.gz",
"https://cloud.r-project.org/src/contrib/laGP_1.5-5.tar.gz",
"https://cloud.r-project.org/src/contrib/mboost_2.9-1.tar.gz",
"https://cloud.r-project.org/src/contrib/mldr_0.4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/mmpf_0.0.5.tar.gz",
"https://cloud.r-project.org/src/contrib/mRMRe_2.0.9.tar.gz",
"https://cloud.r-project.org/src/contrib/nodeHarvest_0.7-3.tar.gz",
"https://cloud.r-project.org/src/contrib/numDeriv_2016.8-1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/pander_0.6.3.tar.gz",
"https://cloud.r-project.org/src/contrib/penalized_0.9-51.tar.gz",
"https://cloud.r-project.org/src/contrib/PMCMR_4.3.tar.gz",
"https://cloud.r-project.org/src/contrib/praznik_7.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rappdirs_0.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/refund_0.1-17.tar.gz",
"https://cloud.r-project.org/src/contrib/rgenoud_5.8-3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/ROCR_1.0-7.tar.gz",
"https://cloud.r-project.org/src/contrib/rotationForest_0.1.3.tar.gz",
"https://cloud.r-project.org/src/contrib/RRF_1.9.1.tar.gz",
"https://cloud.r-project.org/src/contrib/rsm_2.10.tar.gz",
"https://cloud.r-project.org/src/contrib/stepPlr_0.93.tar.gz",
"https://cloud.r-project.org/src/contrib/survAUC_1.0-5.tar.gz",
"https://cloud.r-project.org/src/contrib/svglite_1.2.2.tar.gz",
"https://cloud.r-project.org/src/contrib/SwarmSVM_0.1-5.tar.gz",
"https://cloud.r-project.org/src/contrib/tgp_2.4-14.tar.gz",
"https://cloud.r-project.org/src/contrib/wavelets_0.3-0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/lhs_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/akima_0.6-2.tar.gz",
"https://cloud.r-project.org/src/contrib/cmaesr_1.0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/DiceOptim_2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/BatchJobs_1.8.tar.gz",
"https://cloud.r-project.org/src/contrib/Rmpi_0.6-9.tar.gz",
"https://cloud.r-project.org/src/contrib/blob_1.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/DBItest_1.5-2.tar.gz",
"https://cloud.r-project.org/src/contrib/haven_2.2.0.tar.gz",
"https://cloud.r-project.org/src/contrib/modelr_0.1.5.tar.gz",
"https://cloud.r-project.org/src/contrib/readxl_1.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/reprex_0.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/feather_0.3.5.tar.gz",
"https://cloud.r-project.org/src/contrib/DiagrammeR_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/Ckmeans.1d.dp_4.3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/float_0.2-3.tar.gz",
"https://cloud.r-project.org/src/contrib/doParallel_1.0.15.tar.gz",
"https://cloud.r-project.org/src/contrib/FactoMineR_1.42.tar.gz",
"https://cloud.r-project.org/src/contrib/multcomp_1.4-10.tar.gz",
"https://cloud.r-project.org/src/contrib/fda_2.4.8.tar.gz",
"https://cloud.r-project.org/src/contrib/chemometrics_1.4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/combinat_0.0-8.tar.gz",
"https://cloud.r-project.org/src/contrib/questionr_0.7.0.tar.gz",
"https://cloud.r-project.org/src/contrib/scatterplot3d_0.3-41.tar.gz",
"https://cloud.r-project.org/src/contrib/som_0.3-5.1.tar.gz",
"https://cloud.r-project.org/src/contrib/deldir_0.1-23.tar.gz",
"https://cloud.r-project.org/src/contrib/pec_2019.11.03.tar.gz",
"https://cloud.r-project.org/src/contrib/prodlim_2019.10.13.tar.gz",
"https://cloud.r-project.org/src/contrib/imbalance_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/RcppEigen_0.3.3.5.0.tar.gz",
"https://cloud.r-project.org/src/contrib/gmp_0.5-13.5.tar.gz",
"https://cloud.r-project.org/src/contrib/mvoutlier_2.0.9.tar.gz",
"https://cloud.r-project.org/src/contrib/glasso_1.11.tar.gz",
"https://cloud.r-project.org/src/contrib/matrixcalc_1.0-3.tar.gz",
"https://cloud.r-project.org/src/contrib/NeuralNetTools_1.5.2.tar.gz",
"https://cloud.r-project.org/src/contrib/entropy_1.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/corpcor_1.6.9.tar.gz",
"https://cloud.r-project.org/src/contrib/fdrtool_1.2.15.tar.gz",
"https://cloud.r-project.org/src/contrib/crossval_1.0.3.tar.gz",
"https://cloud.r-project.org/src/contrib/rJava_0.9-11.tar.gz",
"https://cloud.r-project.org/src/contrib/mvtnorm_1.0-11.tar.gz",
"https://cloud.r-project.org/src/contrib/partykit_1.2-5.tar.gz",
"https://cloud.r-project.org/src/contrib/randomForest_4.6-14.tar.gz",
"https://cloud.r-project.org/src/contrib/rjson_0.2.20.tar.gz",
"https://cloud.r-project.org/src/contrib/getopt_1.20.3.tar.gz",
"https://cloud.r-project.org/src/contrib/rlist_0.4.6.1.tar.gz",
"https://cloud.r-project.org/src/contrib/C50_0.1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/cowplot_1.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/RWeka_0.4-41.tar.gz",
"https://cloud.r-project.org/src/contrib/caret_6.0-84.tar.gz",
"https://cloud.r-project.org/src/contrib/R.utils_2.9.0.tar.gz",
"https://cloud.r-project.org/src/contrib/readr_1.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/car_3.0-4.tar.gz",
"https://cloud.r-project.org/src/contrib/rrcov_1.4-7.tar.gz",
"https://cloud.r-project.org/src/contrib/VIM_4.8.0.tar.gz",
"https://cloud.r-project.org/src/contrib/bartMachine_1.2.4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/ada_2.0-5.tar.gz",
"https://cloud.r-project.org/src/contrib/h2o_3.26.0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/XML_3.98-1.20.tar.gz",
"https://cloud.r-project.org/src/contrib/e1071_1.7-2.tar.gz",
"https://cloud.r-project.org/src/contrib/DescTools_0.99.30.tar.gz",
"https://cloud.r-project.org/src/contrib/dplyr_0.8.3.tar.gz",
"https://cloud.r-project.org/src/contrib/devtools_2.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/libcoin_1.0-5.tar.gz",
"https://cloud.r-project.org/src/contrib/earth_5.1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/inum_1.0-1.tar.gz",
"https://cloud.r-project.org/src/contrib/httr_1.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/gh_1.0.1.tar.gz",
"https://cloud.r-project.org/src/contrib/plotly_4.9.1.tar.gz",
"https://cloud.r-project.org/src/contrib/plotrix_3.7-6.tar.gz",
"https://cloud.r-project.org/src/contrib/party_1.3-3.tar.gz",
"https://cloud.r-project.org/src/contrib/RCurl_1.95-4.12.tar.gz",
"https://cloud.r-project.org/src/contrib/usethis_1.5.1.tar.gz",
"https://cloud.r-project.org/src/contrib/covr_3.3.2.tar.gz",
"https://cloud.r-project.org/src/contrib/roxygen2_6.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/rversions_2.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/plotmo_3.5.6.tar.gz",
"https://cloud.r-project.org/src/contrib/curl_4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/openssl_1.4.1.tar.gz",
"https://cloud.r-project.org/src/contrib/smoof_1.5.1.tar.gz",
"https://cloud.r-project.org/src/contrib/rvest_0.3.5.tar.gz",
"https://cloud.r-project.org/src/contrib/ModelMetrics_1.2.2.tar.gz",
"https://cloud.r-project.org/src/contrib/xml2_1.2.2.tar.gz",
"https://cloud.r-project.org/src/contrib/fs_1.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/gbm_2.1.5.tar.gz",
"https://cloud.r-project.org/src/contrib/git2r_0.26.1.tar.gz",
"https://cloud.r-project.org/src/contrib/hashmap_0.2.2.tar.gz",
"https://cloud.r-project.org/src/contrib/shiny_1.4.0.tar.gz",
"https://cloud.r-project.org/src/contrib/glmnet_3.0.tar.gz",
"https://cloud.r-project.org/src/contrib/jsonlite_1.6.tar.gz",
"https://cloud.r-project.org/src/contrib/kknn_1.3.1.tar.gz",
"https://cloud.r-project.org/src/contrib/mlr_2.15.0.tar.gz",
"https://cloud.r-project.org/src/contrib/mlrMBO_1.1.2.tar.gz",
"https://cloud.r-project.org/src/contrib/parallelMap_1.4.tar.gz",
"https://cloud.r-project.org/src/contrib/rpart.plot_3.0.8.tar.gz",
"https://cloud.r-project.org/src/contrib/RPostgres_1.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/rstudioapi_0.10.tar.gz",
"https://cloud.r-project.org/src/contrib/stringr_1.4.0.tar.gz",
"https://cloud.r-project.org/src/contrib/tictoc_1.0.tar.gz",
"https://cloud.r-project.org/src/contrib/tidyverse_1.2.1.tar.gz",
"https://cloud.r-project.org/src/contrib/xgboost_0.90.0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/adabag_4.2.tar.gz",
"https://cloud.r-project.org/src/contrib/deepnet_0.2.tar.gz",
"https://cloud.r-project.org/src/contrib/DiscriMiner_0.1-29.tar.gz",
"https://cloud.r-project.org/src/contrib/elasticnet_1.1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/evtree_1.0-8.tar.gz",
"https://cloud.r-project.org/src/contrib/extraTrees_1.0.5.tar.gz",
"https://cloud.r-project.org/src/contrib/fda.usc_1.5.0.tar.gz",
"https://cloud.r-project.org/src/contrib/FNN_1.1.3.tar.gz",
"https://cloud.r-project.org/src/contrib/kernlab_0.9-28.tar.gz",
"https://cloud.r-project.org/src/contrib/klaR_0.6-14.tar.gz",
"https://cloud.r-project.org/src/contrib/LiblineaR_2.10-8.tar.gz",
"https://cloud.r-project.org/src/contrib/liquidSVM_1.2.4.tar.gz",
"https://cloud.r-project.org/src/contrib/mda_0.4-10.tar.gz",
"https://cloud.r-project.org/src/contrib/pls_2.7-2.tar.gz",
"https://cloud.r-project.org/src/contrib/randomForestSRC_2.9.1.tar.gz",
"https://cloud.r-project.org/src/contrib/ranger_0.11.2.tar.gz",
"https://cloud.r-project.org/src/contrib/rFerns_3.0.0.tar.gz",
"https://cloud.r-project.org/src/contrib/rknn_1.2-1.tar.gz",
"https://cloud.r-project.org/src/contrib/rrlda_1.1.tar.gz",
"https://cloud.r-project.org/src/contrib/RSNNS_0.4-12.tar.gz",
"https://cloud.r-project.org/src/contrib/sda_1.3.7.tar.gz",
"https://cloud.r-project.org/src/contrib/sparseLDA_0.1-9.tar.gz",
"https://cloud.r-project.org/src/contrib/tuneRanger_0.5.tar.gz"
)

# libs <- unique(c(
# "rpart",
#     "rJava",
# "mvtnorm",
# "partykit",
# "randomForest",
# "rjson",
# "getopt",
# "rlist",
# "C50",
# "cowplot",
# "RWeka",
# "caret",
# "R.utils",
# "readr",
# "car",
# "rrcov",
# "VIM",
# "bartMachine",
# "C50",
# "ada",
# "h2o",
# "caret",
# "XML",
# "e1071",
# "DescTools",
# "dplyr",
# "devtools",
# "libcoin",
# "earth",
# "inum",
# "httr",
# "gh",
# "plotly",
# "plotrix",
# "party",
# "RCurl",
# "usethis",
# "covr",
# "roxygen2",
# "rversions",
# "plotmo",
# "curl",
# "openssl",
# "smoof",
# "rvest",
# "ModelMetrics",
# "xml2",
# "fs",
# "gbm",
# "getopt",
# "git2r",
# "hashmap",
# "shiny",
# "glmnet",
# "jsonlite",
# "kknn",
# "plotmo",
# "mlr",
# "mlrMBO",
# "parallelMap",
# "randomForest",
# "readr",
# "rjson",
# "rpart.plot",
# "rpart.plot",
# "RPostgres",
# "rstudioapi",
# "stringr",
# "tictoc",
# "tidyverse",
# "xgboost",
# "RWeka",
# "adabag", #NAI
# "bartMachine",
# "C50",
# "caret",
# "class", #NAI
# "deepnet", #NAI
# "DescTools",
# "devtools",
# "DiscriMiner", #NAI
# "dplyr",
# "e1071",
# "earth",
# "elasticnet", #NAI
# "evtree", #NAI
# "extraTrees", #NAI
# "fda.usc", #NAI
# "FNN", #NAI
# "fs",
# "gbm",
# "getopt",
# "git2r",
# "glmnet",
# "h2o",
# "httr",
# "jsonlite",
# "kernlab", #NAI
# "kknn",
# "klaR", #NAI
# "LiblineaR", #NAI
# "liquidSVM",
# "MASS", #NAI
# "mda", #NAI
# "mlr", #install_version("mlr", version = "2.14.0", repos = "http://cran.us.r-project.org")
# "mlrMBO",
# "nnet", #NAI
# "parallel",
# "parallelMap",
# "party",
# "pls", #NAI
# "randomForest",
# "randomForestSRC",
# "ranger", #NAI
# "readr",
# "rFerns", #NAI
# "rjson",
# "rknn", #NAI
# "rpart",
# "rpart.plot",
# "RPostgres",
# "rrlda", #NAI
# "RSNNS", #NAI
# "RWeka", #NAI
# "rstudioapi",
# "sda", #NAI
# "sparseLDA", #NAI
# "stringr",
# "tictoc",
# "tidyverse",
# "tuneRanger",
# "xgboost"
# ))

new.packages <- libs[!(libs %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, repos=NULL, type="source", dependencies = TRUE)

for(l in new.packages) {

    AP <- available.packages()
    if(!(l %in% AP[,1])) {
        print(paste("Failed to install", l))
        quit(status = 1, save= 'no')
    }

    if ( ! library(l, character.only=TRUE, logical.return=TRUE) ) {
        quit(status = 2, save='no')
    }
}

devtools::install_github("ja-thomas/autoxgboost")
devtools::install_github("berndbischl/ParamHelpers") # version >= 1.11 needed.
devtools::install_github("jakob-r/mlrHyperopt", dependencies = TRUE)

wekalibs <- c("multiBoostAB", "lazyBayesianRules")
library(RWeka)
WPM("refresh-cache")
for(l in wekalibs) {
    WPM("install-package", l)
}

